import nodemailer from 'nodemailer';

export async function sendFailureMail(email: string, url: string, location: string) {
    const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: process.env.EMAIL_USER!,
            pass: process.env.EMAIL_PASS!,
        },
    });

    const mailOptions = {
        from: `"Uptime Monitor" <${process.env.EMAIL_USER!}>`,
        to: email,
        subject: '🚨 Your Website is DOWN!',
        text: `ALERT: Your website ${url} is reported as DOWN by a validator from ${location}.`,
        html: `
            <div style="font-family: Arial, sans-serif; padding: 20px; background: #f8f9fa;">
                <div style="max-width: 600px; margin: auto; background: white; border-radius: 8px; box-shadow: 0 0 10px rgba(0,0,0,0.1); overflow: hidden;">
                    <div style="background-color: #dc3545; color: white; padding: 20px; text-align: center;">
                        <h2 style="margin: 0;">🚨 Website Down Alert</h2>
                    </div>
                    <div style="padding: 20px;">
                        <p>Hey there,</p>
                        <p><strong>Your website is down:</strong></p>
                        <p style="font-size: 16px; margin: 10px 0; padding: 10px; background-color: #f1f1f1; border-radius: 4px;">
                            <a href="${url}" target="_blank">${url}</a>
                        </p>
                        <p>This was reported by a validator located in <strong>${location}</strong>.</p>
                        <p>Please take immediate action to check your server or hosting provider.</p>
                        <br>
                        <p style="font-size: 12px; color: #888;">This alert was generated by your uptime monitoring system.</p>
                    </div>
                    <div style="background-color: #f1f1f1; padding: 10px; text-align: center;">
                        <img src="https://i.imgur.com/HW1QXcP.png" alt="Alert" style="max-width: 100px; margin-top: 10px;" />
                    </div>
                </div>
            </div>
        `,
    };

    try {
        await transporter.sendMail(mailOptions);
        console.log(`📩 Email sent to ${email}`);
    } catch (err) {
        console.error('❌ Failed to send email:', err);
    }
}
